version: "3.8"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres               # Usa el mismo usuario de PrestaBanco
      POSTGRES_PASSWORD: alonsoreyes104     # La misma contraseña que usas actualmente
      POSTGRES_DB: PrestaBanco              # Conéctate a la base de datos PrestaBanco
    ports:
      - "5432:5432"

  pgadmin: 
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: nicolas.munoz.r@usach.cl
      PGADMIN_DEFAULT_PASSWORD: password      # Cambia la contraseña si lo prefieres
    ports:
      - "80:80"
    depends_on:
      - postgres
  # frontend services
  frontend1:
    image: ttoto104/frontend:latest
    networks:
      - frontend-network
  frontend2:
    image: ttoto104/frontend:latest
    networks:
      - frontend-network
  frontend3:
    image: ttoto104/frontend:latest
    networks:
      - frontend-network

  # backend services
  backend1:
    image: ttoto104/backend:latest
    environment:
      - DB_HOST=192.168.56.1
    networks:
      - backend-network
  backend2:
    image: ttoto104/backend:latest
    environment:
      - DB_HOST=192.168.56.1
    networks:
      - backend-network
  backend3:
    image: ttoto104/backend:latest
    environment:
      - DB_HOST=192.168.56.1
    networks:
      - backend-network

  # Nginx for frontend load balancing
  nginx-frontend:
    image: nginx:latest
    ports:
      - "8070:80"
    volumes:
      - ./nginx-frontend.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend1
      - frontend2
      - frontend3
    networks:
      - frontend-network

  # Nginx for backend load balancing
  nginx-backend:
    image: nginx:latest
    ports:
      - "8090:8090"
    volumes:
      - ./nginx-backend.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend1
      - backend2
      - backend3
    networks:
      - backend-network

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge
# docker compose up
# docker compose down