pipeline {
    agent any
    tools{
        maven 'maven_3_8_1'
    }
    stages{
        stage('Build maven'){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/NicolasAMunozR/TingesoLab1-Backend']])
                bat 'mvn clean package'
            }
        }

        stage('Unit Tests') {
            steps {
                dir('backend') { // Cambia a la carpeta 'backend'
                    bat 'mvn clean package' // o 'bat' si estás en Windows
                }
            }
        }

        stage('Build docker image'){
            steps{
                script{
                    bat 'docker build -t t-toto104/backend:latest .'
                }
            }
        }
        stage('Push image to Docker Hub'){
            steps{
                script{
                   withCredentials([string(credentialsId: 'T_Toto104', variable: 'dhpsw')]) {
                        bat 'docker login -u t-toto104 -p %dhpsw%'
                   }
                   bat 'docker push t-toto104/backend:latest'
                }
            }
        }
    }
}